metrics_enabled: true
debug: false
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - io.dropwizard
    - com.hello

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  streams :
    sense_sensors_data : sense_sensors_data

firehose:
  region: us-east-1
  stream: prod_sense_data

app_name: SenseFirehoseProd

max_records: 300

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.hello.suripu.firehose: DEBUG
  # Settings for logging to a file.
  appenders:
        - type: file
          threshold: DEBUG
          currentLogFilename: /var/log/suripu-firehose/suripu-firehose-sense.log
          archivedLogFilenamePattern: /var/log/suripu-firehose/suripu-firehose-sense-%d{yyyy-MM-dd}.log.gz
          archivedFileCount: 7
          timeZone: UTC

dynamodb:
  region: us-east-1
  default_endpoint: http://dynamodb.us-east-1.amazonaws.com
  tables:
    alarm_info: prod_alarm_info
    features: features
  endpoints: {}